num =(input('Digite algo '))
print('Esse dado é de qual tipo primitivo: ', type(num))
print('Esse dado é númerico? ', num.isnumeric())
print('Esse dado é alpha numérico? ', num.isalnum())
print('Esse dado foi digitado todo em letra minúscula? ', num.islower())
print('Esse dado foi digitado todo em letra maiúscula? ', num.isupper())
print('Esse dado foi digitado de forma capitalizada? ', num.istitle())
print('Esse dado é alfabético? ', num.isalpha())
print('Esse dado só tem espaços?', num.isspace())
